-- core/map_tag_dummy.lua
-- Provides dummy force and chart tag objects for test environments

local function get_dummy_chart_tag(map_tag, player, pos)
  ---@type LuaForce
  local dummy_force = {
    name = "test-force",
    object_name = "LuaForce",
    add_chart_tag = function() return {} end,
    valid = true,
    print = function() end,
    ai_controllable = true,
    artillery_range_modifier = 0,
    beacon_distribution_modifier = 0,
    belt_stack_size_bonus = 0,
    bulk_inserter_capacity_bonus = 0,
    character_build_distance_bonus = 0,
    character_health_bonus = 0,
    character_inventory_slots_bonus = 0,
    character_item_drop_distance_bonus = 0,
    character_item_pickup_distance_bonus = 0,
    character_logistic_requests = true,
    character_loot_pickup_distance_bonus = 0,
    character_reach_distance_bonus = 0,
    character_resource_reach_distance_bonus = 0,
    character_running_speed_modifier = 0,
    character_trash_slot_count = 0,
    circuit_network_enabled = true,
    cliff_deconstruction_enabled = true,
    color = {r=1,g=1,b=1,a=1},
    connected_players = {},
    create_ghost_on_entity_death = true,
    deconstruction_time_to_live = 0,
    following_robots_lifetime_modifier = 0,
    friendly_fire = true,
    index = 1,
    inserter_stack_size_bonus = 0,
    items_launched = {},
    laboratory_productivity_bonus = 0,
    laboratory_speed_modifier = 0,
    logistic_networks = {},
    manual_crafting_speed_modifier = 0,
    manual_mining_speed_modifier = 0,
    max_failed_attempts_per_tick_per_construction_queue = 0,
    max_successful_attempts_per_tick_per_construction_queue = 0,
    maximum_following_robot_count = 0,
    mining_drill_productivity_bonus = 0,
    mining_with_fluid = true,
    platforms = {},
    players = {},
    rail_planner_allow_elevated_rails = true,
    rail_support_on_deep_oil_ocean = true,
    recipes = {},
    research_enabled = true,
    research_progress = 0,
    research_queue = {},
    rockets_launched = 0,
    share_chart = true,
    technologies = {},
    train_braking_force_bonus = 0,
    vehicle_logistics = true,
    worker_robots_battery_modifier = 0,
    worker_robots_speed_modifier = 0,
    worker_robots_storage_bonus = 0,
    add_research = function() end,
    cancel_charting = function() end,
    cancel_current_research = function() end,
    chart = function() end,
    chart_all = function() end,
    clear_chart = function() end,
    copy_chart = function() end,
    copy_from = function() end,
    create_space_platform = function() end,
    disable_all_prototypes = function() end,
    disable_research = function() end,
    enable_all_prototypes = function() end,
    enable_all_recipes = function() end,
    enable_all_technologies = function() end,
    enable_research = function() end,
    find_chart_tags = function() return {} end,
    find_logistic_network_by_position = function() end,
    get_ammo_damage_modifier = function() return 0 end,
    get_cease_fire = function() return false end,
    get_entity_build_count_statistics = function() return {} end,
    get_entity_count = function() return 0 end,
    get_evolution_factor = function() return 0 end,
    get_evolution_factor_by_killing_spawners = function() return 0 end,
    get_evolution_factor_by_pollution = function() return 0 end,
    get_evolution_factor_by_time = function() return 0 end,
    get_fluid_production_statistics = function() return {} end,
    get_friend = function() return false end,
    get_gun_speed_modifier = function() return 0 end,
    get_hand_crafting_disabled_for_recipe = function() return false end,
    get_item_launched = function() return 0 end,
    get_item_production_statistics = function() return {} end,
    get_kill_count_statistics = function() return {} end,
    get_linked_inventory = function() return {} end,
    get_spawn_position = function() return {x=0,y=0} end,
    get_surface_hidden = function() return false end,
    get_turret_attack_modifier = function() return 0 end,
    is_chunk_charted = function() return false end,
    is_chunk_requested_for_charting = function() return false end,
    is_chunk_visible = function() return false end,
    is_enemy = function() return false end,
    is_friend = function() return false end,
    is_pathfinder_busy = function() return false end,
    is_quality_unlocked = function() return false end,
    is_space_location_unlocked = function() return false end,
    is_space_platforms_unlocked = function() return false end,
    kill_all_units = function() end,
    lock_quality = function() end,
    lock_space_location = function() end,
    lock_space_platforms = function() end,
    play_sound = function() end,
    rechart = function() end,
    research_all_technologies = function() end,
    reset = function() end,
    reset_evolution = function() end,
    reset_recipes = function() end,
    reset_technologies = function() end,
    reset_technology_effects = function() end,
    set_ammo_damage_modifier = function() end,
    set_cease_fire = function() end,
    set_evolution_factor = function() end,
    set_evolution_factor_by_killing_spawners = function() end,
    set_evolution_factor_by_pollution = function() end,
    set_evolution_factor_by_time = function() end,
    set_friend = function() end,
    set_gun_speed_modifier = function() end,
    set_hand_crafting_disabled_for_recipe = function() end,
    set_item_launched = function() end,
    set_spawn_position = function() end,
    set_surface_hidden = function() end,
    set_turret_attack_modifier = function() end,
    unchart_chunk = function() end,
    unlock_quality = function() end,
    unlock_space_location = function() end,
    unlock_space_platforms = function() end
  }
  ---@cast dummy_force LuaForce
  local dummy_chart_tag = {
    valid = true,
    position = pos,
    text = map_tag.gps,
    last_user = player, -- LuaPlayer?
    force = dummy_force,
    icon = { type = "item", name = "iron-plate" }, -- dummy SignalID
    object_name = "LuaCustomChartTag",
    surface = player.surface,
    tag_number = 1,
    print = function() end,
    destroy = function() end
  }
  return dummy_chart_tag
end

return {
  get_dummy_chart_tag = get_dummy_chart_tag
}
